# Hydrangea Dark Night
[colors]
foreground = "#616571"
background = "#070a13"
cursor_bg = "#65002f"
cursor_border = "#65002f"
cursor_fg = "#070a13"
selection_bg = "#1e576b"
selection_fg = "#679eb4"

ansi = [
    "#222530",
    "#4b001c",
    "#274313",
    "#4b541c",
    "#233769",
    "#471c7b",
    "#004155",
    "#787c89",
]
brights = [
    "#616571",
    "#9a2559",
    "#698755",
    "#a8b47a",
    "#627bb3",
    "#8964c8",
    "#4f859b",
    "#c1c6d4",
]

