# Hydrangea Bright Night
[colors]
foreground = "#8c909e"
background = "#292c38"
cursor_bg = "#980057"
cursor_border = "#980057"
cursor_fg = "#292c38"
selection_bg = "#488299"
selection_fg = "#91cde6"

ansi = [
    "#484b58",
    "#7d0041",
    "#506d3c",
    "#758048",
    "#4a6196",
    "#704aab",
    "#306b81",
    "#a5a9b7",
]
brights = [
    "#8c909e",
    "#d12f85",
    "#96b681",
    "#d8e5a8",
    "#8fa9e3",
    "#b793fb",
    "#78b4cb",
    "#f2f7ff",
]

