# Hydrangea Bright Night
[colors]
foreground = "#6f737f"
background = "#12151e"
cursor_bg = "#76003c"
cursor_border = "#76003c"
cursor_fg = "#12151e"
selection_bg = "#2a657a"
selection_fg = "#73aec4"

ansi = [
    "#2e323c",
    "#5c0028",
    "#355021",
    "#59632b",
    "#304577",
    "#542c8b",
    "#0e4f63",
    "#868b97",
]
brights = [
    "#6f737f",
    "#ad2968",
    "#779664",
    "#b8c589",
    "#718ac2",
    "#9874d9",
    "#5a95ab",
    "#d1d6e4",
]

