# Hydrangea Dark Night
[colors]
foreground = "#383c47"
background = "#000000"
cursor_bg = "#33000c"
cursor_border = "#33000c"
cursor_fg = "#000000"
selection_bg = "#112d42"
selection_fg = "#516f86"

ansi = [
    "#03040c",
    "#1c0001",
    "#031c00",
    "#252c0f",
    "#030e3d",
    "#23004d",
    "#001a2d",
    "#4d515d",
]
brights = [
    "#383c47",
    "#641a31",
    "#3f5a38",
    "#7b8464",
    "#394f83",
    "#5f4795",
    "#3b586e",
    "#9297a4",
]

